### ISSUE TITLE
failure to resize disk

### ISSUE THREAD

**Issue by rafaelmartins** [prometheanfire/gentoo-cloud-prep#11]
This seems to be the only failure I get now, with recent images from today (July 20). Everything else works fine :)

```
Jul 21 01:52:58 localhost util.py[DEBUG]: Running command ['gpart', 'recover', '/dev/vda'] with allowed return codes [0] (shell=False, capture=True)
Jul 21 01:52:58 localhost util.py[WARNING]: Failed: gpart recover /dev/vda
Jul 21 01:52:58 localhost util.py[DEBUG]: Failed: gpart recover /dev/vda
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/cloudinit/config/cc_growpart.py", line 132, in resize
    util.subp(["gpart", "recover", diskdev])
  File "/usr/lib64/python2.7/site-packages/cloudinit/util.py", line 1570, in subp
    cmd=args)
ProcessExecutionError: Unexpected error while running command.
Command: ['gpart', 'recover', '/dev/vda']
Exit code: 1
Reason: -
Stdout: ''
Stderr: 'Usage: gpart [options] device\nOptions: [-b <backup MBR>][-C c,h,s][-c][-d][-E][-e][-f][-g][-h][-i]\n         [-K <last sector>][-k <# of sectors>][-L][-l <log file>]\n         [-n <increment>][-q][-s <sector-size>][-t <module-name>]\n         [-V][-v][-W <device>][-w <module-name,weight>]\ngpart v0.1h (c) 1999-2001 Michail Brzitwa <michail@brzitwa.de>.\nGuess PC-type hard disk partitions.\n\n'
Jul 21 01:52:58 localhost util.py[DEBUG]: resize_devices took 0.017 seconds
Jul 21 01:52:58 localhost cc_growpart.py[DEBUG]: '/' FAILED: failed to resize: disk=/dev/vda, ptnum=2: Unexpected error while running command.
Command: ['gpart', 'recover', '/dev/vda']
Exit code: 1
Reason: -
Stdout: ''
Stderr: 'Usage: gpart [options] device\nOptions: [-b <backup MBR>][-C c,h,s][-c][-d][-E][-e][-f][-g][-h][-i]\n         [-K <last sector>][-k <# of sectors>][-L][-l <log file>]\n         [-n <increment>][-q][-s <sector-size>][-t <module-name>]\n         [-V][-v][-W <device>][-w <module-name,weight>]\ngpart v0.1h (c) 1999-2001 Michail Brzitwa <michail@brzitwa.de>.\nGuess PC-type hard disk partitions.\n\n'
Jul 21 01:52:58 localhost stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib64/python2.7/site-packages/cloudinit/config/cc_resizefs.pyc'>) with frequency always
Jul 21 01:52:58 localhost helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x29b91fbe990>)
Jul 21 01:52:58 localhost util.py[DEBUG]: Reading from /proc/3509/mountinfo (quiet=False)
Jul 21 01:52:58 localhost util.py[DEBUG]: Read 2051 bytes from /proc/3509/mountinfo
Jul 21 01:52:58 localhost cc_resizefs.py[DEBUG]: resize_info: dev=/dev/vda2 mnt_point=/ path=/
```

**Comment by prometheanfire** [comment]
fixed in https://github.com/prometheanfire/gentoo-cloud-prep/commit/83f7f2c34f98bb1821403047ea520bae6e43b79d
