### ISSUE TITLE
syslog user not found, when trying to chown /var/log/cloud-init.log

### ISSUE THREAD

**Issue by prometheanfire** [prometheanfire/gentoo-cloud-prep#5]

**Comment by prometheanfire** [comment]
I think the user is hardcoded

**Comment by hartwork** [comment]
The default is hardcoded, but it can be configured in `/etc/cloud/cloud.cfg`.

**Comment by rafaelmartins** [comment]
```
Jul  2 18:06:37 localhost util.py[DEBUG]: Cloud-init v. 0.7.6 running 'init-local' at Thu, 02 Jul 2015 18:06:37 +0000. Up 10.97 seconds.
Jul  2 18:06:37 localhost util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [420] 0 bytes
Jul  2 18:06:37 localhost util.py[WARNING]: Unable to change the ownership of /var/log/cloud-init.log to user syslog, group adm
Jul  2 18:06:37 localhost util.py[DEBUG]: Unable to change the ownership of /var/log/cloud-init.log to user syslog, group adm
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/cloudinit/stages.py", line 156, in _initialize_filesystem
    util.chownbyname(log_file, u, g)
  File "/usr/lib64/python2.7/site-packages/cloudinit/util.py", line 1134, in chownbyname
    raise OSError("Unknown user or group: %s" % (e))
OSError: Unknown user or group: 'getpwnam(): name not found: syslog'
```

**Comment by travisghansen** [comment]
I think the option for this one is: syslog_fix_perms: root:root
