### ISSUE TITLE
failure to generate ecdsa host key (fixed it manually?)

### ISSUE THREAD

**Issue by prometheanfire** [prometheanfire/gentoo-cloud-prep#7]

**Comment by prometheanfire** [comment]
needinfo

**Comment by rafaelmartins** [comment]
```
Jul  2 18:06:45 localhost util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=False)
Jul  2 18:06:45 localhost util.py[WARNING]: Failed generating key type ecdsa to file /etc/ssh/ssh_host_ecdsa_key
Jul  2 18:06:45 localhost util.py[DEBUG]: Failed generating key type ecdsa to file /etc/ssh/ssh_host_ecdsa_key
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/cloudinit/config/cc_ssh.py", line 103, in handle
    util.subp(cmd, capture=False)
  File "/usr/lib64/python2.7/site-packages/cloudinit/util.py", line 1570, in subp
    cmd=args)
ProcessExecutionError: Unexpected error while running command.
Command: ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key']
Exit code: 1
Reason: -
Stdout: ''
Stderr: ''
```

this is a quite generic one. :/

**Comment by travisghansen** [comment]
This is from the bindist use flag.
Resolution is rebuild ssh or add to cloud.cfg: ssh_genkeytypes: [rsa, dsa]

https://github.com/travisghansen/gentoo-cloud-image-builder/blob/master/builder/cloud.cfg#L21
