### ISSUE TITLE
failure to run debconf-set-selections (wtf?), some random python failure, etc

### ISSUE THREAD

**Issue by prometheanfire** [prometheanfire/gentoo-cloud-prep#8]

**Comment by prometheanfire** [comment]
can probably remove the debconf stuff from the cloud.cfg file

needinfo on python thing

**Comment by rafaelmartins** [comment]
dpkg:

```
Jul  2 18:06:46 localhost stages.py[DEBUG]: Running module grub-dpkg (<module 'cloudinit.config.cc_grub_dpkg' from '/usr/lib64/python2.7/site-packages/cloudinit/config/cc_grub_dpkg.pyc'>) with frequency once-per-instance
Jul  2 18:06:46 localhost util.py[DEBUG]: Writing to /var/lib/cloud/instances/9088da02-bd26-49ae-8ed4-1182e8897a5b/sem/config_grub_dpkg - wb: [420] 20 bytes
Jul  2 18:06:46 localhost helpers.py[DEBUG]: Running config-grub-dpkg using lock (<FileLock using file '/var/lib/cloud/instances/9088da02-bd26-49ae-8ed4-1182e8897a5b/sem/config_grub_dpkg'>)
Jul  2 18:06:46 localhost cc_grub_dpkg.py[DEBUG]: Setting grub debconf-set-selections with '/dev/vda','false'
Jul  2 18:06:46 localhost util.py[DEBUG]: Running command ['debconf-set-selections'] with allowed return codes [0] (shell=False, capture=True)
Jul  2 18:06:46 localhost util.py[WARNING]: Failed to run debconf-set-selections for grub-dpkg
Jul  2 18:06:46 localhost util.py[DEBUG]: Failed to run debconf-set-selections for grub-dpkg
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/cloudinit/config/cc_grub_dpkg.py", line 67, in handle
    util.subp(['debconf-set-selections'], dconf_sel)
  File "/usr/lib64/python2.7/site-packages/cloudinit/util.py", line 1565, in subp
    raise ProcessExecutionError(cmd=args, reason=e)
ProcessExecutionError: Unexpected error while running command.
Command: ['debconf-set-selections']
Exit code: -
Reason: [Errno 2] No such file or directory
Stdout: ''
Stderr: ''
```

python:

```
Jul  2 18:06:46 localhost util.py[WARNING]: Running module apt-configure (<module 'cloudinit.config.cc_apt_configure' from '/usr/lib64/python2.7/site-packages/cloudinit/config/cc_apt_configure.pyc'>) failed
Jul  2 18:06:46 localhost util.py[DEBUG]: Running module apt-configure (<module 'cloudinit.config.cc_apt_configure' from '/usr/lib64/python2.7/site-packages/cloudinit/config/cc_apt_configure.pyc'>) failed
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/cloudinit/stages.py", line 660, in _run_modules
    cc.run(run_name, mod.handle, func_args, freq=freq)
  File "/usr/lib64/python2.7/site-packages/cloudinit/cloud.py", line 63, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib64/python2.7/site-packages/cloudinit/helpers.py", line 197, in run
    results = functor(*args)
  File "/usr/lib64/python2.7/site-packages/cloudinit/config/cc_apt_configure.py", line 55, in handle
    mirrors = find_apt_mirror_info(cloud, cfg)
  File "/usr/lib64/python2.7/site-packages/cloudinit/config/cc_apt_configure.py", line 258, in find_apt_mirror_info
    mirror_info = cloud.datasource.get_package_mirror_info()
  File "/usr/lib64/python2.7/site-packages/cloudinit/sources/__init__.py", line 212, in get_package_mirror_info
    availability_zone=self.availability_zone)
  File "/usr/lib64/python2.7/site-packages/cloudinit/distros/__init__.py", line 114, in get_package_mirror_info
    arch_info = self._get_arch_package_mirror_info(arch)
  File "/usr/lib64/python2.7/site-packages/cloudinit/distros/__init__.py", line 107, in _get_arch_package_mirror_info
    arch = self.get_primary_arch()
  File "/usr/lib64/python2.7/site-packages/cloudinit/distros/__init__.py", line 99, in get_primary_arch
    arch = os.uname[4]
TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'
```

This error is stupid. `os.uname` is a function :P

Anyway, this code is apt-related, should not be run in gentoo.

**Comment by prometheanfire** [comment]
fixed in master
